In [1]:

#question 1
import numpy as np
x=np.random.rand(10,1)
print("Formed Matrix Is \n",x)

print("Mean Of The Above Matrix Is =",np.mean(x))

Formed Matrix Is 
 [[0.59380235]
 [0.12736049]
 [0.05283797]
 [0.04278661]
 [0.72654254]
 [0.72777527]
 [0.8538841 ]
 [0.49350861]
 [0.05115406]
 [0.63987533]]
Mean Of The Above Matrix Is = 0.43095273338006856


In [2]:

#Question 2

x=np.random.rand(20,1)
print("Formed Matrix Is \n",x)
print("Variance of the formed matrix is =",np.var(x))
print("Standard deviation of the formed matrix is =",np.std(x))


Formed Matrix Is 
 [[0.53945451]
 [0.8193769 ]
 [0.12068897]
 [0.08597572]
 [0.41143547]
 [0.83833803]
 [0.60538072]
 [0.26204944]
 [0.08725738]
 [0.86473062]
 [0.0720168 ]
 [0.8439209 ]
 [0.47761207]
 [0.45376228]
 [0.96905703]
 [0.42265137]
 [0.73560542]
 [0.09232736]
 [0.62434711]
 [0.6802518 ]]
Variance of the formed matrix is = 0.08560117528979981
Standard deviation of the formed matrix is = 0.29257678528857994


In [3]:

#Question 3

A=np.random.rand(10,20)
B=np.random.rand(20,25)

x=np.matmul(A,B)
print("Matrix Formed After Multiplication\n",x)

print("Sum Of Newly Formed Matrix = ",np.sum(x))

Matrix Formed After Multiplication
 [[4.84924554 5.50677416 4.8499376  5.91296792 4.95600919 5.24900923
  4.92250355 5.5339074  5.0267564  5.18018373 5.48631186 5.19337691
  4.86038683 5.08039215 5.35363209 3.76759954 4.87573702 5.21997048
  4.06184905 5.14362926 5.17529707 5.55067668 5.10734381 5.24360247
  5.56751193]
 [4.09860788 4.95853797 3.87490116 5.71915464 4.89018183 4.95130248
  4.23377791 4.36209656 4.78032881 4.86903408 4.58410042 5.08445086
  4.86464882 5.45097606 5.01913554 3.40624977 4.86388932 4.58871568
  4.32522105 4.07189332 3.98409717 4.77683134 5.02939579 5.04113763
  4.05025081]
 [4.97178481 7.34924276 6.03165191 5.49068565 6.24858847 7.00920722
  6.84559355 6.75622265 6.56384469 6.84910606 6.33977183 5.78230504
  5.88413472 7.17261122 5.81315616 5.10760745 6.6493597  5.53363927
  5.02638186 6.36079397 6.18856666 6.57559575 5.46980024 6.38844409
  6.81189979]
 [5.04875558 5.97311495 4.62293335 4.90364957 4.50544511 4.81086768
  5.4444787  5.32970871 5.46786827 4.7

In [4]:

#Question 4
#f(x)=1 / (1 + exp(-x)) 
from math import exp
y=np.random.rand(10,1)
print(y)
l=[]
for i in y:
    l.append(1/(1+exp(-(i))))
    
print("\n\n\nAfter performing given function")
print(np.array(l).reshape(10,1))

[[0.68829197]
 [0.63008664]
 [0.3086601 ]
 [0.4448593 ]
 [0.35920756]
 [0.43221792]
 [0.51544008]
 [0.9156084 ]
 [0.49444258]
 [0.36023663]]



After performing given function
[[0.66558686]
 [0.65250911]
 [0.57655817]
 [0.60941629]
 [0.58884859]
 [0.60640316]
 [0.62608089]
 [0.71414644]
 [0.62115243]
 [0.58909772]]
